# sets up an instance of sunpi.co server
version: '2'
services:
  # https://github.com/kylemanna/docker-openvpn/blob/master/docs/docker-compose.md
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn

  mysql_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - mysql_db
    image: wordpress:latest
    ports:
      - 8000:8000
    restart: always
    links:
      - mysql_db


